-- 코드를 입력하세요
SELECT RENTAL.CAR_ID, RENTAL.CAR_TYPE, FLOOR(DAILY_FEE*(100-DISCOUNT_RATE)/100*30) AS FEE FROM (
    SELECT CRCC.CAR_ID, CRCC.CAR_TYPE, CRCC.DAILY_FEE 
    FROM CAR_RENTAL_COMPANY_CAR AS CRCC JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH ON CRCC.CAR_ID=CRCRH.CAR_ID 
    WHERE (CRCC.CAR_TYPE='세단' OR CRCC.CAR_TYPE='SUV')
    AND CRCC.CAR_ID NOT IN (
        SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30') 
    GROUP BY CRCC.CAR_ID
) AS RENTAL JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP ON RENTAL.CAR_TYPE = CRCDP.CAR_TYPE
WHERE CRCDP.DURATION_TYPE='30일 이상'
AND DAILY_FEE*(100-DISCOUNT_RATE)/100*30 >= 500000 
AND DAILY_FEE*(100-DISCOUNT_RATE)/100*30 < 2000000
ORDER BY FEE DESC, RENTAL.CAR_TYPE, RENTAL.CAR_ID DESC;