-- 코드를 작성해주세요
SELECT ED.ID, ED.GENOTYPE, ED2.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS ED JOIN ECOLI_DATA AS ED2 ON ED.PARENT_ID = ED2.ID
WHERE ED.GENOTYPE & ED2.GENOTYPE = ED2.GENOTYPE
ORDER BY ED.ID;